# Generated by Django 5.0.6 on 2024-06-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_information_vetement_info_technique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetement',
            old_name='info_technique',
            new_name='information_Technique',
        ),
    ]
