# Generated by Django 5.0.6 on 2024-06-23 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_info_technique_vetement_information_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetement',
            name='nouveau_prix',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetement',
            name='publié',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
